### ISSUE TITLE
Footer Nav

### ISSUE THREAD

**Issue by brian-frederick** [brian-frederick/HPNC-Umbraco-Site#11]
from @vemigh: 
Dark gray bottom section
About Us
Remove Board Documents, we will want that on the actual Board of Directors page instead
Four categories: Board of Directors, Staff Directory, Newsletters, Annual Reports
Contact Us
Switch out “Staff Directory” for email address: info@hpnclub.org
 get links working for google maps

**Comment by brian-frederick** [comment]
@vemigh are these four categories all intended to be linked to internal pages? I don't believe newsletter or annual reports pages exist. We have a staff page - is that the staff directory we'd link to?

**Comment by vemigh** [comment]
Yes, they would be links to our own pages. We would need new pages for newsletter and annual report. They should have links to pdfs of our recent newsletters or the last couple of annual reports. We would need to be able to upload new documents and create links. Yes, the staff directory would be the existing staff page.

**Comment by brian-frederick** [comment]
@vemigh ok. creating new tasks for those new pages.

**Comment by vemigh** [comment]
Yes, that's correct!

**Comment by brian-frederick** [comment]
@vemigh this is ready for you to qa. the newsletter and annual report links go to the staff page bc those pages don't exist yet. we can change those footer links while creating those pages.

**Comment by vemigh** [comment]
Looks good, thanks!
