### ISSUE TITLE
Volunteer Page Edits

### ISSUE THREAD

**Issue by brian-frederick** [brian-frederick/HPNC-Umbraco-Site#21]
Volunteer
Top of page should feature three photo circles before header
Can we embed a form within the site itself that exports into an excel document for the volunteer coordinator? Could that be editable?

**Comment by brian-frederick** [comment]
Embed Google Form? Think about security considerations.

@vemigh Can you add what the fields should be for this and which ones would be required.

**Comment by brian-frederick** [comment]
worst case scenario, we just have a link to a google form.

**Comment by brian-frederick** [comment]
@vemigh can you tell us which fields you'd like on this form?

**Comment by vemigh** [comment]
This form will be great, thank you. I just requested access through our hpnc gmail account, hpnclub5480@gmail.com, so that we can edit from there.
