### ISSUE TITLE
Program Partners Page

### ISSUE THREAD

**Issue by brian-frederick** [brian-frederick/HPNC-Umbraco-Site#25]
Top of page should feature three photo circles before header
Here we will include logos of partners, descriptions of their offerings, and links to their own pages

**Comment by brian-frederick** [comment]
@vemigh 
Ability to upload logos, add descriptions, and links to pages
use staff page as template

**Comment by vemigh** [comment]
duplicate of staff page

**Comment by brian-frederick** [comment]
@vemigh this page can be seen at http://hpnclub.azurewebsites.net/program-partners

**Comment by vemigh** [comment]
Excellent, thank you! 

One last thing: the program partners circle on the home page should link directly to this page.

**Comment by brian-frederick** [comment]
@vemigh that's done! for future reference, you can configure where those circles link to.

**Comment by vemigh** [comment]
Perfect, thank you!!
