### ISSUE TITLE
Make Photos Circular

### ISSUE THREAD

**Issue by brian-frederick** [brian-frederick/HPNC-Umbraco-Site#6]
Our other stylistic element is circles so as much as possible we want to incorporate those into the design. For instance, if photos could be circles that would be great. Right now the photos seem oval, can they be circles? I’m not sure if that is something we need crop beforehand or if the site can turn photos into circles after uploading.

**Comment by brian-frederick** [comment]
@vemigh - hmmm, let me know where you're seeing ovals. we can apply the circular pattern through css or through image cropping.

**Comment by vemigh** [comment]
The photos on the home page look like ovals (slightly wider than they are tall) not circles, or is that just a trick of my imagination? Or the top of the "Volunteer" "Basketball" and "After School"?

**Comment by brian-frederick** [comment]
huh. let's look at these together.

**Comment by brian-frederick** [comment]
@vemigh is this resolved?

**Comment by vemigh** [comment]
Yes, thanks!
