### ISSUE TITLE
Round Corners on colored text boxes 

### ISSUE THREAD

**Issue by brian-frederick** [brian-frederick/HPNC-Umbraco-Site#7]
If we ever use a special colored text box, we typically make those rectangles with rounded corners, would that be possible in this site too?

**Comment by brian-frederick** [comment]
@vemigh are there some specific cases you can reference here?

**Comment by vemigh** [comment]
It's really just the "volunteer" and "donate" buttons, I guess. Can they have rounded corners?

**Comment by vemigh** [comment]
Kind of like the various "Register" buttons

**Comment by brian-frederick** [comment]
gotcha. easy fix.
