### ISSUE TITLE
Conform Colors

### ISSUE THREAD

**Issue by brian-frederick** [brian-frederick/HPNC-Umbraco-Site#8]
Colors: You have our color swatches already, right? (it certainly looks like it)
headers on pages should be in our colors according to program type:
Early Childhood: Orange
Enrichment (Athletics):	Green
Mentoring: Blue
Out of School Time (Elementary): Yellow
Community (Board, Staff, Volunteer): Dark Gray
Program Partners: Light Gray
Other body text should be gray when on a white background (it looks like it pretty much already is

**Comment by brian-frederick** [comment]
@vemigh can you clarify what you mean by "headers on pages"?

**Comment by vemigh** [comment]
Just the name of the program at the top of the page for example: "Basketball" "After School K-8" "Mentoring"

**Comment by brian-frederick** [comment]
@vemigh makes sense. would you mind providing those color swatches again?
